config/routes.rb
Rails.application.routes.draw do
  

 

  get 'password_resets/new'

  get 'password_resets/edit'

  root "articles#index"
  get 'plan_lekcji' => 'static_pages#timetable'
  get 'kontakt' => 'static_pages#contact'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :articles
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts, only: [:new, :create]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>Created by Irek Wróbel</small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container"> 
    <%= link_to "logo" , root_path, id: "logo" %>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </button>
         </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Plan lekcji", plan_lekcji_path %></li>
              <li><%= link_to "Kontakt", kontakt_path %></li>
              <li><%= link_to "Czat", new_post_path %></li>
            </ul>
            <% if logged_in? %>
          <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Konto <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li><%= link_to "Ustawienia", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Wyloguj", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Rejestracja", new_user_path %></li>
          <li><%= link_to "Zaloguj się", login_path %></li>
          </ul>
        <% end %>
          </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class='container'>
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= render 'shared/sidebar' unless @disable_sidebar %>
    <div class="col-md-8 col-sm-9 col-xs-12 yield">
      <%= yield %>
    </div>
	</div>
</body>
</html>